### ISSUE TITLE
Show miniatures for images

### ISSUE THREAD

**Issue by Gerlot** [spacecowboy/NoNonsense-FilePicker#10]
Hi!
This file picker library is really cool, but I have one suggestion. It would be really good if the file picker can show miniatures for image files. I think I'm not the only one who would appreciate this! Keep up the good work, and thanks!

**Comment by spacecowboy** [comment]
It's a cool idea. But not something I will implement as the library works well for my purposes. If anyone were to submit a patch with that feature though, I'd be happy to include it.

**Comment by spacecowboy** [comment]
Hey, finally got some time on my hands so I implemented this in a new sample app:

https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/v2.0.3

I want to keep the main library as minimal as possible, so it won't be included in the library direct but because it's so easy to do by extending a class that shouldn't be much of an issue for you :)

See this file for an example of how it's done:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/java/com/nononsenseapps/filepicker/sample/ImagePickerFragment.java
