### ISSUE TITLE
Add external, Internal, and USB storage support

### ISSUE THREAD

**Issue by Programming4life** [spacecowboy/NoNonsense-FilePicker#18]
Is there external, Internal, and USB storage support? For example let the user pick from external or Internal or USB storage instead of just having it default to one.

**Comment by spacecowboy** [comment]
No special handling is needed for these usecases. These are just folders which you can browse to. For example

- Internal: `/storage/sdcard0` or `/storage/emulated/0` (This if the default folder if none is specified)
- External: `/storage/sdcard1/`

You can get these paths from the system using `android.os.Environment.getExternalStorageDirectory()` method and others.

Where USB Storage is mounted depends on the app you use to mount it, since it's still not supported entirely by android itself?. But likely it will be somwhere under `/storage/` or `/mnt/`

You can specify the folder which is opened on start with an argument to the intent:

    intent.putStringExtra(AbstractFilePickerActivity.EXTRA_START_PATH, "/storage/sdcard1/")

It would be trivial to extend the FilePicker I have included to block the user from leaving the external SD-card if that's what you want. Would just need to edit `getRoot()` and `getParent()` basically.
