### ISSUE TITLE
Customising display of file names

### ISSUE THREAD

**Issue by hcoosthuizen** [spacecowboy/NoNonsense-FilePicker#38]
I have a small problem in which long file names are ellipsized, but I need the entire file name to display.  Would it be possible to include some form of customisation to allow the items to be multiline or the names to be marqueed?

I'd really rather not duplicate the majority of the code just to change the display of the filename, if possible.

**Comment by spacecowboy** [comment]
Sure. I'll take a stab at it.

**Comment by spacecowboy** [comment]
This is quite easy to do as is without duplicating any code. You just need to override `onCreateViewHolder` and load your own layout.

Here's the result:
![nononsensefilepicker - -workspace-nononsensefilepicker - sample - -workspace-nononsensefilepicker-sample-src-main-res-layout-longer_listitem_dir xml - android studio 1 3_028](https://cloud.githubusercontent.com/assets/223655/9005608/d1373ae2-377f-11e5-8311-d2da8affa7bf.png)

I copied the two listitem layouts and modified them so the text can span up to 4 lines, naming them `longer_listitem_dir.xml` and `longer_listitem_checkable.xml` respectively. Then I created a fragment to use these layouts instead of the default:

```java
public class LongerListItemFragment extends FilePickerFragment {
    /**
     * @param parent Containing view
     * @param viewType which the ViewHolder will contain. Should be either checkable, "dir" (non-checkable) or header (which is shown like "dir" by default).
     * @return a view holder for a file or directory
     */
    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View v;
        switch (viewType) {
            case LogicHandler.VIEWTYPE_HEADER:
                v = LayoutInflater.from(getActivity()).inflate(R.layout.longer_listitem_dir,
                        parent, false);
                return new HeaderViewHolder(v);
            case LogicHandler.VIEWTYPE_CHECKABLE:
                v = LayoutInflater.from(getActivity()).inflate(R.layout.longer_listitem_checkable,
                        parent, false);
                return new CheckableViewHolder(v);
            case LogicHandler.VIEWTYPE_DIR:
            default:
                v = LayoutInflater.from(getActivity()).inflate(R.layout.longer_listitem_dir,
                        parent, false);
                return new DirViewHolder(v);
        }
    }
}
```

I'll put a full example up in the wiki here:
https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Custom-listitem-layouts-to-display-long-filenames

Is this a suitable solution to your usecase?

**Comment by hcoosthuizen** [comment]
That's perfect.  I thought of overriding the method, but wasn't sure if I'd end up breaking something else in the process, suppose I should have just experimented.  Thanks for the speedy reply and keep up the good work :)
