### ISSUE TITLE
Only allow selecting single files (when EXTRA_ALLOW_MULTIPLE is set to false)

### ISSUE THREAD

**Issue by Gerlot** [spacecowboy/NoNonsense-FilePicker#48]
In the intent you can currently specify if you want to enable the selection of multiple items (EXTRA_ALLOW_MULTIPLE), but it only affects directory selection. If you use MODE_FILE, the checkboxes near files are always showing and the above option has no effect.

It would be great if when you set EXTRA_ALLOW_MULTIPLE to false, and MODE_FILE, a single click on a file would open it, and no checkboxes would be visible.

**Comment by Gerlot** [comment]
Ok, I realized that when the EXTRA_ALLOW_MULTIPLE is set to false, you can only check one checkbox, and thus only select one file. But still, I think it's a bit confusing? Isn't the way I described better (no checkboxes, and open files on click)?

**Comment by spacecowboy** [comment]
It's certainly a way. I'll think about it for a bit.

**Comment by spacecowboy** [comment]
OK, I've thought about it. While I personally prefer the current behavior, your question did raise the issue that it's not particularly easy to override this behavior atm. To adress this I have made a few changes for 2.4.0 that will allow you to easily get the desired behavior.

I'll add a full example to the Wiki, but here's basically how it can be done in 2.4.0:

```java
public class SingleFilePickerFragment extends FilePickerFragment {
    @Override
    public void onClickCheckable(View v, CheckableViewHolder vh) {
        super.onClickCheckable(v, vh);
        if (!allowMultiple) {
            // User has selected the item of choice, close and return.
            onClickOk(null);
        }
    }
}
```

This is the most straight-forward way. However, it will still animate checking the checkbox as the window is closing (since we called onClickOk()), so a slightly better way is:

```java
    @Override
    public void onClickCheckable(View v, CheckableViewHolder vh) {
        if (!allowMultiple) {
            mCheckedItems.add(vh.file);
            onClickOk(null);
        } else {
            super.onClickCheckable(v, vh);
        }
    }
```

Which does not tick the checkbox. No point since the user won't have time to see it anyway.

**Comment by Gerlot** [comment]
Yeah, before I created the issue, I tried implementing the behaviour by overriding methods, but I couldn't. This solution you came up, is verry neat, thank you!

And the lib is becoming more useful every day, I was watching it for a while, and now I'm using it in one of my projects. It's awesome that it's so easy to extend and shape it to fulfill different needs!

**Comment by spacecowboy** [comment]
That's the general plan :)

**Comment by spacecowboy** [comment]
2.4.0 has been pushed to jcenter now btw.

**Comment by spacecowboy** [comment]
And here's an example in the Wiki:

https://github.com/spacecowboy/NoNonsense-FilePicker/wiki/Example:-Override-what-happens-when-you-click-on-stuff-in-the-list

Note that the example code I gave you previously has a small bug in it (doesn't clear previous selections).

**Comment by Gerlot** [comment]
Awesome, thank you! I'll get into it right away. ;)
