### ISSUE TITLE
Black color for FilePicker title with Light Theme?

### ISSUE THREAD

**Issue by RazorPT** [spacecowboy/NoNonsense-FilePicker#61]
Hi there, i just noticed that if we use the light theme the title in the action bar is in black color when it should be white no? Like your example images? Or am i doing something wrong?

Thanks for developing this awesome library

**Comment by spacecowboy** [comment]
Hi.

Material design themes allow you to specify a separate theme for the toolbar. The default theme colors the text black, assuming you want a really bright background. I don't to override system defaults, so that's why I don't change this by default.

To change the toolbar theme, have a look at the [Sample's theme](https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/res/values/styles.xml)

```xml
<style name="SampleThemeLight" parent="NNF_BaseTheme.Light">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>

        <item name="alertDialogTheme">@style/SampleAlertDialogThemeLight</item>

        <!-- Make sure toolbar title is white -->
        <item name="nnf_toolbarTheme">@style/SampleToolbarTheme</item>
</style>

<style name="SampleToolbarTheme" parent="ThemeOverlay.AppCompat.Dark.ActionBar">
        <item name="android:textColorPrimary">@android:color/white</item>
</style>
```

As you can see, you can specify any theme values you like this way.
