### ISSUE TITLE
Question: How to open the file picker in a dialog?

### ISSUE THREAD

**Issue by GeorgeChackungal** [spacecowboy/NoNonsense-FilePicker#62]
I looked over the wiki and the examples but couldn't see a way to open the filepicker as a dialog as shown in the screen shots. Can you please help?

**Comment by spacecowboy** [comment]
Standard behavior is to open as a dialog on large screens. This typically means a tablet with a 7inch or larger screen.

This is controlled by the theme which you load the filepicker with, so you can override this behavior if you want. The samples suggest that you inherit from the `NNF_BaseTheme` (or light version) included in the library, which you can see here:
[styles.xml](https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/res/values/styles.xml)

So you if want to load the picker as a dialog, no matter what size the screen is, just use a theme which inherits from `Dialog` instead of `DialogWhenLarge`, such as:

```xml
    <style name="DialogFilePickerTheme" parent="Theme.AppCompat.Dialog">
        <!-- Insert your ColorPrimary, ColorPrimaryDark, and ColorAccent values here, 
             plus whatever else you might want to have in the theme -->

        <!-- Change these if you like -->
        <item name="nnf_toolbarTheme">@style/ThemeOverlay.AppCompat.ActionBar</item>
        <item name="nnf_separator_color">@color/nnf_dark_separator_color</item>

        <!-- These are important. Don't remove them. -->
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
```

**Comment by GeorgeChackungal** [comment]
Worked Beautifully! Thanks :+1:
