### ISSUE TITLE
Change license to MPL

### ISSUE THREAD

**Issue by RazorPT** [spacecowboy/NoNonsense-FilePicker#66]
I am not sure but i think LGPL libraries cant be used on android projects unless they can be updated separately from the app which is not possible on android since the final app is a apk or the app it self is open sourced. So why not change to Apache License? Or this was intended?

Thank you for developing such awesome library :)

**Comment by spacecowboy** [comment]
Thanks for saying so :)

The LGPL does not have the limitation that you mention. In short, the LGPL allows you to use the library freely for both personal and commercial purposes (so far, just like Apache).

The limitation of the LGPL is that you must make the source code of this library available to the users of your app. Which means nothing if you don't want to change anything. If anyone asks, you just send them here.

The way it differs from Apache is if you make any changes to the library's code. Then, the license requires that you provide your users with the modified source code, which the Apache license does not require. In other words, the LGPL does not allow people to fork the project and create a modified library and then keep that code secret.

Note however, that it does not force someone who forks the project to make that fork open source. It only requires that the *users* of the app must have access to the library's source code. If they agree to keep it secret, then that's fine.

And the LGPL differs from the GPL, in that the GPL would require you to make the source code of your entire app available to your users, not just this library. So the license should not pose any limitation to you, even if your app is a payed closed source app.

So to answer your final question, my intention is that modifications to the library should be made available to the users, so that others also may continue to improve it.

**Comment by RazorPT** [comment]
Well from what i read there are many different opinions on the subject, some say its fine other say it violates section d) 1)

http://stackoverflow.com/questions/4916512/using-lgpl-library-in-paid-android-app
http://blog.xebia.com/the-lgpl-on-android/
http://programmers.stackexchange.com/questions/205925/use-of-lgpl-libraries-in-closed-source-android-software

Section d) 1) states:
[use runtime linking against a copy already present on the system, and allow
       the user to replace that copy]

You can read here:
http://blog.xebia.com/the-lgpl-on-android/

There are divergent opinions on the matter, and that's why Google went for Apache License on their source code:
http://source.android.com/source/licenses.html#why-apache-software-license

I do understand that this way any modification to your source code has to be open source and respect that, but i really not sure how compliant is to use LGPL software on android :)

**Comment by spacecowboy** [comment]
Interesting. Seems I was not aware of all aspects of the license. 

I need to do some reading, but on a first glance, the [Mozilla Public License 2.0](https://tldrlegal.com/license/mozilla-public-license-2.0-%28mpl-2%29) seems to be more inline with my intentions. Another possibility might be the [Eclipse Public License](https://tldrlegal.com/license/eclipse-public-license-1.0-%28epl-1.0%29).

Thanks for bringing it to my attention.

**Comment by RazorPT** [comment]
Hi again i think you are correct Mozilla Public License and Eclipse Public License don't seem to have the dynamic linking requirement and still preserve the requirement that any change to the library must be open sourced, so they are safe to use on Android :)

**Comment by rastikw** [comment]
Hello, have you decided on the licence change? I'd like to use your library in my project, but LGPL is too strict (commercial project). I already have some ideas for improvements, so with Mozilla or Eclipse licence I'd generate a pull request. Thank you.

**Comment by spacecowboy** [comment]
Yes I think I'll go with the MPL. just need to actually update the repo.
Can do that today so you can get on with your things :)
