### ISSUE TITLE
Color theme from attributes

### ISSUE THREAD

**Issue by fmeneuhe** [spacecowboy/NoNonsense-FilePicker#69]
Hi,
First of all congrats for the lib.
Is possible to modify the lib to get the primary, primaryDark and accent colors from attributes and not from resources vaalues like "@color/primary"?
My app gets all the colors from the Android "?attr/colorPrimary", because users can select the theme at runtime.

Ah, trying in FilePickerTheme.xml this does not work, it crashes inflating xml:
```
<style name="FilePickerTheme" parent="NNF_BaseTheme">
        <item name="colorPrimary">?attr/colorPrimary</item>
```

**Comment by spacecowboy** [comment]
What does the crash log say? I suspect the problem is that you're trying to set colorPrimary to itself. Note that since the filepicker uses its own theme, it doesn't know what you have defined in the theme of the rest of your app.

So to follow the style which is set at runtime, you need to set the theme on the filepicker at runtime as well.

So just override the filepicker activity and launch that. Just override the oncreate method and set a suitable theme (probably just as you do in your main app activity). For example, 

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        // Get shared preferences with current theme
        ...
       String selectedTheme = sharedPrefs.getString("currentSelectedTheme");

        if (dark.equals(selectedTheme)) {
            context.setTheme(R.style.DarkTheme);
        } else if (black.equals(selectedTheme)) {
            context.setTheme(R.style.BlackTheme);
        } else {
            // light
            context.setTheme(R.style.LightTheme);
        }
        super.onCreate(savedInstanceState);
    }
```

**Comment by fmeneuhe** [comment]
I tried to read the colorPrimary from my app, and I see now thats not possible.
The solution is to create different themes as you say (like my app does now), I just tried to avoid that but is the only solution.
Thanks
